### ISSUE TITLE
Здравствуйте!

### ISSUE THREAD

**Issue by SCherkass** [FBGhost-community/FBG-Cura-Definitions#13]
Благодарю за труд! Небольшое пожелание - вы предполагаете установку с помощью exe- файла для Windows. Можно-ли создать краткое описание (или, по-возможности лучше скрипт) для установки на macOs? Благодарю!

**Comment by c0rv4x** [comment]
@SCherkass 

Добрый день, я нашел описание под мак в вики вот тут https://fbghost.info/bin/view/Main/5.%20%D0%9F%D1%80%D0%BE%D0%B3%D1%80%D0%B0%D0%BC%D0%BC%D0%BD%D0%B0%D1%8F%20%D1%87%D0%B0%D1%81%D1%82%D1%8C/%D0%9D%D0%B5%D0%BE%D1%84%D0%B8%D1%86%D0%B8%D0%B0%D0%BB%D1%8C%D0%BD%D1%8B%D0%B9%20%D0%BF%D1%80%D0%BE%D1%84%D0%B8%D0%BB%D1%8C%20%D0%BF%D1%80%D0%B8%D0%BD%D1%82%D0%B5%D1%80%D0%B0%20%D0%B4%D0%BB%D1%8F%20Cura/

`Ctrl+F -> Mac`

**Comment by oducceu** [comment]
Добрый день! Есть надежда, что в следующем релизе профиль будет устанавливаться уже вместе с курой официально. https://github.com/Ultimaker/Cura/pull/7243

**Comment by SCherkass** [comment]
> @SCherkass
> 
> Добрый день, я нашел описание под мак в вики вот тут https://fbghost.info/bin/view/Main/5.%20%D0%9F%D1%80%D0%BE%D0%B3%D1%80%D0%B0%D0%BC%D0%BC%D0%BD%D0%B0%D1%8F%20%D1%87%D0%B0%D1%81%D1%82%D1%8C/%D0%9D%D0%B5%D0%BE%D1%84%D0%B8%D1%86%D0%B8%D0%B0%D0%BB%D1%8C%D0%BD%D1%8B%D0%B9%20%D0%BF%D1%80%D0%BE%D1%84%D0%B8%D0%BB%D1%8C%20%D0%BF%D1%80%D0%B8%D0%BD%D1%82%D0%B5%D1%80%D0%B0%20%D0%B4%D0%BB%D1%8F%20Cura/
> 
> `Ctrl+F -> Mac`

Благодарю за ответ. Я конечно-же ручками все проделал.
